In [1]:
import requests
import pandas as pd
for i in range(2008,2019):
 url = 'https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_' + str(i) + '.csv'
 res = requests.get(url, allow_redirects=True)
 with open('atp_matches_'+ str(i) + '.csv','wb') as file:
    file.write(res.content)
 matches = pd.read_csv('atp_matches_'+ str(i) + '.csv')

In [2]:
import torch
import torchvision
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import torch.nn as nn
import torch.nn.functional as F
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor
from torchvision.utils import make_grid
from torch.utils.data.dataloader import DataLoader
from torch.utils.data import random_split
%matplotlib inline

# Use a white background for matplotlib figures
matplotlib.rcParams['figure.facecolor'] = '#ffffff'

In [3]:
import csv
import matplotlib.pyplot as plt
import numpy as np
import json
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier

def getdays(date1):
	year1 = int(date1[0] + date1[1] + date1[2] + date1[3])
	month1 = int(date1[4] + date1[5])
	date1 = int(date1[6] + date1[7])

	answer = 365*year1 + 30*month1 + date1
	return answer

def getmonth(date1):
	month1 = int(date1[4] + date1[5])
	return month1

# Reorders all csv files to fixed column ordering and loads to a ndarray
def create_add_year_matches(input_path, output_path):

	with open(input_path, 'r') as infile, open(output_path, 'w') as outfile:
	    # Output dict needs a list for new column ordering
	    fieldnames = ['tourney_id', #0
	                  'tourney_name', #1
	                  'surface', #2
	                  'draw_size', #3
	                  'tourney_level', #4
	                  'tourney_date', #5
	                  'match_num', #6
	                  'winner_id', #7
	                  'winner_seed', #8
	                  'winner_entry', #9
	                  'winner_name', #10
	                  'winner_hand', #11
	                  'winner_ht', #12
	                  'winner_ioc', #13
	                  'winner_age', #14
	                  'winner_rank', #15
	                  'winner_rank_points', #16
	                  'loser_id', #17
	                  'loser_seed', #18
	                  'loser_entry', #19
	                  'loser_name', #20
	                  'loser_hand', #21
	                  'loser_ht', #22
	                  'loser_ioc', #23
	                  'loser_age', #24
	                  'loser_rank', #25
	                  'loser_rank_points', #26
	                  'score', #27
	                  'best_of', #28
	                  'round', #29
	                  'minutes', #30
	                  'w_ace', #31
	                  'w_df', #32
	                  'w_svpt', #33
	                  'w_1stIn', #34
	                  'w_1stWon', #35
	                  'w_2ndWon', #36
	                  'w_SvGms', #37
	                  'w_bpSaved', #38
	                  'w_bpFaced', #39
	                  'l_ace', #40
	                  'l_df', #41
	                  'l_svpt', #42
	                  'l_1stIn', #43
	                  'l_1stWon', #44
	                  'l_2ndWon', #45
	                  'l_SvGms', #46
	                  'l_bpSaved', #47
	                  'l_bpFaced'] #48

	    writer = csv.DictWriter(outfile, fieldnames=fieldnames)
	    # reorder the header first
	    writer.writeheader()
	    for row in csv.DictReader(infile):
	        # writes the reordered rows to the new file
	        writer.writerow(row)

	inputs = np.loadtxt(output_path, dtype=np.dtype(str), delimiter=',', skiprows=1)
	return inputs

with open('atp_matches_2018.csv', 'r') as infile, open('reordered_atp_matches_2018.csv', 'w') as outfile:
    # output dict needs a list for new column ordering
    fieldnames = ['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level', 'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry', 'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age', 'winner_rank', 'winner_rank_points' ,'loser_id', 'loser_seed'	,'loser_entry', 'loser_name', 'loser_hand', 'loser_ht' , 'loser_ioc', 'loser_age', 'loser_rank', 'loser_rank_points', 'score', 'best_of' ,'round', 'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon', 'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt', 'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced']

    writer = csv.DictWriter(outfile, fieldnames=fieldnames)
    # reorder the header first
    writer.writeheader()
    for row in csv.DictReader(infile):
        # writes the reordered rows to the new file
        writer.writerow(row)

inputs = np.loadtxt("reordered_atp_matches_2018.csv", dtype=np.dtype(str), delimiter=',', skiprows=1)

for i in range(2008,2018):
	input_path = 'atp_matches_' + str(i) + '.csv'
	output_path = 'reordered_atp_matches' + str(i) + '.csv'

	inputs_temp = create_add_year_matches(input_path, output_path)
	inputs = np.concatenate((inputs, inputs_temp))

print(inputs.shape)

(32783, 49)


In [4]:
# def create_difference_of_players(inputs,head_to_head,rank__track):
#     x=np.zeros((18627,2))
#     for i in range(0,18627):
#         if (inputs[i][7],inputs[i][17]) in head_to_head and (inputs[i][7],inputs[i][17]) in rank__track:
#           (a1,a2)=head_to_head[(inputs[i][7],inputs[i][17])]
#           (a3,a4)=rank__track[(inputs[i][7],inputs[i][17])]
#           x[i][0]=a3-a4
#           x[i][1]=a1-a2
#     return x

Record ranking and head to head of two players in a separate Dictionary 

In [5]:
head_to_head=dict()
rank__track=dict()

In [6]:
for i in range(0,len(inputs)):
  if (inputs[i][7],inputs[i][17])  in head_to_head:
   (a1,a2,x,y)=head_to_head[(inputs[i][7],inputs[i][17])]
   a1=a1+1
   head_to_head[(inputs[i][7],inputs[i][17])]=(a1,a2,1,0)
  elif(inputs[i][17],inputs[i][7]) in head_to_head:
    (a3,a4,x,y)=head_to_head[(inputs[i][17],inputs[i][7])]
    a4=a4+1
    head_to_head[(inputs[i][17],inputs[i][7])]=(a3,a4,0,1)
  else:
    head_to_head[(inputs[i][7],inputs[i][17])]=(1,0,1,0)

In [7]:
for i in range(0,len(inputs)):
  if (inputs[i][7],inputs[i][17]) not in rank__track:
   rank__track[(inputs[i][7],inputs[i][17])]=(inputs[i][16],inputs[i][26])

Store the difference of ranking and head to head of the  two players in a dictionary

In [8]:
input_dict=dict()
targets_dict=dict()
for i in range(0,18627):
  if ((inputs[i][7],inputs[i][17]) not in input_dict) and (inputs[i][7],inputs[i][17]) in head_to_head and (inputs[i][7],inputs[i][17]) in rank__track:
    (a1,a2,x,y)=head_to_head[(inputs[i][7],inputs[i][17])]
    (a3,a4)=rank__track[(inputs[i][7],inputs[i][17])]
    if a3!='' and a4!='':
     input_dict[(inputs[i][7],inputs[i][17])]=(float(a3)-float(a4),float(a1)-float(a2))
     targets_dict[(inputs[i][7],inputs[i][17])]=(x,y)

In [9]:

count=0
for i in range(0,len(inputs)):
  if(inputs[i][7],inputs[i][17]) in input_dict:
   count=count+1
count

19189

In [10]:
dataset=np.zeros((count,2),dtype='float')
targets=np.zeros((count,1),dtype='float')
for i in range(0,count):
 if(inputs[i][7],inputs[i][17]) in input_dict:
   dataset[i][0]=input_dict[(inputs[i][7],inputs[i][17])][0]
   dataset[i][1]=input_dict[(inputs[i][7],inputs[i][17])][1]
   if targets_dict[(inputs[i][7],inputs[i][17])][0]==1:
     targets[i]=0
   else:
      targets[i]=1

In [11]:
dataset=torch.from_numpy(dataset)
dataset

tensor([[ 1.0100e+02,  0.0000e+00],
        [ 2.9700e+02,  2.0000e+00],
        [-5.8200e+02, -1.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00],
        [ 4.8900e+03,  7.0000e+00],
        [ 0.0000e+00,  0.0000e+00]], dtype=torch.float64)

In [12]:
targets=torch.from_numpy(targets)
targets

tensor([[1.],
        [0.],
        [1.],
        ...,
        [0.],
        [0.],
        [0.]], dtype=torch.float64)

In [13]:
matches=torch.cat((dataset,targets),1)
matches

tensor([[ 1.0100e+02,  0.0000e+00,  1.0000e+00],
        [ 2.9700e+02,  2.0000e+00,  0.0000e+00],
        [-5.8200e+02, -1.0000e+00,  1.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 4.8900e+03,  7.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]], dtype=torch.float64)

In [14]:
from torch.utils.data import random_split
val_size = int(0.1*len(matches))
train_size = len(matches) - val_size
train_ds, val_ds = random_split(matches, [train_size,val_size])
len(train_ds), len(val_ds)

(17271, 1918)

In [15]:
batch_size=128
train_loader = DataLoader(train_ds, batch_size, num_workers=4, pin_memory=True)
val_loader = DataLoader(val_ds, batch_size*2, num_workers=4, pin_memory=True)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


In [16]:
class MnistModel(nn.Module):
    """Feedfoward neural network with 1 hidden layer"""
    def __init__(self, in_size, hidden_size, out_size):
        super().__init__()
        # hidden layer
        self.linear1 = nn.Linear(in_size, hidden_size)
        # output layer
        self.linear2 = nn.Linear(hidden_size, out_size)
        
    def forward(self, xb):
        # Flatten the image tensors
        #xb = xb.view(xb.size(0), -1)
        # Get intermediate outputs using hidden layer
        out = self.linear1(xb)
        # Apply activation function
        out = torch.tanh(out)
        # Get predictions using output layer
        out = self.linear2(out)
        return out
    
    def training_step(self, batch):
        matches= batch
        target=torch.flatten(matches[:,2:3].long())
        out = self(matches[:,0:2].float())                  # Generate predictions
        loss = F.cross_entropy(out, target) # Calculate loss
        return loss
    
    def validation_step(self, batch):
        matches = batch 
        target=torch.flatten(matches[:,2:3].long())
        out = self(matches[:,0:2].float())                  # Generate predictions
        loss = F.cross_entropy(out,target)   # Calculate loss
        acc = accuracy(out,target)           # Calculate accuracy
        return {'val_loss': loss, 'val_acc': acc}
        
    def validation_epoch_end(self, outputs):
        batch_losses = [x['val_loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()   # Combine losses
        batch_accs = [x['val_acc'] for x in outputs]
        epoch_acc = torch.stack(batch_accs).mean()      # Combine accuracies
        return {'val_loss': epoch_loss.item(), 'val_acc': epoch_acc.item()}
    
    def epoch_end(self, epoch, result):
        print("Epoch [{}], val_loss: {:.4f}, val_acc: {:.4f}".format(epoch, result['val_loss'], result['val_acc']))

In [17]:
def accuracy(outputs, labels):
    _,preds = torch.max(outputs, dim=1)
    return torch.tensor(torch.sum(preds == labels).item() / len(preds))

In [18]:
input_size = 2
hidden_size = 4
num_classes = 2

In [19]:
model = MnistModel(input_size, hidden_size, out_size=num_classes)

In [20]:
for t in model.parameters():
    print(t.shape)

torch.Size([4, 2])
torch.Size([4])
torch.Size([2, 4])
torch.Size([2])


In [21]:
for matches in train_loader:
    outputs = model(matches[:,0:2].float())
    loss = F.cross_entropy(outputs, torch.flatten(matches[:,2:3].long()))
    print('Loss:', loss.item())
    break

print('outputs.shape : ', outputs.shape)
print('Sample outputs :\n', outputs[:2].data)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


Loss: 0.9922394752502441
outputs.shape :  torch.Size([128, 2])
Sample outputs :
 tensor([[-0.2114,  0.9293],
        [-0.2114,  0.9293]])


GPU Utilities

In [22]:
torch.cuda.is_available()

True

In [23]:
def get_default_device():
    """Pick GPU if available, else CPU"""
    if torch.cuda.is_available():
        return torch.device('cuda')
    else:
        return torch.device('cpu')

In [24]:
device = get_default_device()
device

device(type='cuda')

In [25]:
def to_device(data, device):
    """Move tensor(s) to chosen device"""
    if isinstance(data, (list,tuple)):
        return [to_device(x, device) for x in data]
    return data.to(device, non_blocking=True)

In [26]:
for matches in train_loader:
    print(matches.shape)
    images = to_device(matches, device)
    print(matches.device)
    break

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


torch.Size([128, 3])
cpu


In [27]:
class DeviceDataLoader():
    """Wrap a dataloader to move data to a device"""
    def __init__(self, dl, device):
        self.dl = dl
        self.device = device
        
    def __iter__(self):
        """Yield a batch of data after moving it to device"""
        for b in self.dl: 
            yield to_device(b, self.device)

    def __len__(self):
        """Number of batches"""
        return len(self.dl)

In [28]:
train_loader = DeviceDataLoader(train_loader, device)
val_loader = DeviceDataLoader(val_loader, device)

In [29]:
for xb in val_loader:
    print('xb.device:', xb.device)
    #print('xb:', xb)
    break

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


xb.device: cuda:0


In [30]:
def evaluate(model, val_loader):
    """Evaluate the model's performance on the validation set"""
    outputs = [model.validation_step(batch) for batch in val_loader]
    return model.validation_epoch_end(outputs)

def fit(epochs, lr, model, train_loader, val_loader, opt_func=torch.optim.SGD):
    """Train the model using gradient descent"""
    history = []
    optimizer = opt_func(model.parameters(), lr)
    for epoch in range(epochs):
        # Training Phase 
        for batch in train_loader:
            loss = model.training_step(batch)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
        # Validation phase
        result = evaluate(model, val_loader)
        model.epoch_end(epoch, result)
        history.append(result)
    return history

In [31]:
model = MnistModel(input_size, hidden_size=hidden_size, out_size=num_classes)
to_device(model, device)

MnistModel(
  (linear1): Linear(in_features=2, out_features=4, bias=True)
  (linear2): Linear(in_features=4, out_features=2, bias=True)
)

In [32]:
history = [evaluate(model, val_loader)]
history

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'val_acc': 0.14981709420681, 'val_loss': 1.2289948463439941}]

In [33]:
history += fit(5, 0.5, model, train_loader, val_loader)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


Epoch [0], val_loss: 0.3900, val_acc: 0.8502
Epoch [1], val_loss: 0.3876, val_acc: 0.8502
Epoch [2], val_loss: 0.3867, val_acc: 0.8502
Epoch [3], val_loss: 0.3862, val_acc: 0.8502
Epoch [4], val_loss: 0.3859, val_acc: 0.8502
